name: Build TrollSpeed tIPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Theos & iOS SDK
        run: |
          bash -c "$(curl -fsSL https://githubusercontent.com)"
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          mkdir -p $HOME/theos/sdks
          curl -L https://github.com | tar -xf - -C $HOME/theos/sdks/

      - name: Build and Package
        run: |
          export THEOS=$HOME/theos
          make package

      - name: Upload tIPA Product
        uses: actions/upload-artifact@v4
        with:
          name: TrollSpeed_tIPA_Package
          path: packages/TrollSpeed.tipa
